# Generated by Django 3.2.6 on 2021-08-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('cpf',), 'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
    ]
