# Generated by Django 4.1.3 on 2022-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('type_of_negotiation', models.CharField(choices=[
                 ('a', 'aluguel'), ('v', 'venda')], max_length=1, verbose_name='tipo de negociação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PropertyRent',
            fields=[
            ],
            options={
                'verbose_name': 'aluguel',
                'verbose_name_plural': 'aluguéis',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('realty.realty',),
        ),
        migrations.CreateModel(
            name='PropertySale',
            fields=[
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('realty.realty',),
        ),
    ]
