# Generated by Django 4.1.3 on 2022-12-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='sobrenome')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('rating', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='pontuação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço')),
                ('stock_min', models.PositiveSmallIntegerField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('authors', models.ManyToManyField(blank=True, to='bookstore.author', verbose_name='autores')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
                'ordering': ('title',),
            },
        ),
    ]
