# Generated by Django 4.1.3 on 2022-12-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_publisher_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
