# Generated by Django 3.2.6 on 2021-08-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nf', models.CharField(max_length=100, unique=True, verbose_name='nota fiscal')),
            ],
            options={
                'verbose_name': 'ordem de compra',
                'verbose_name_plural': 'ordens de compra',
                'ordering': ('nf',),
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preço')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='ecommerce.order', verbose_name='ordem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_items', to='product.product', verbose_name='produto')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
