# Generated by Django 4.1.3 on 2022-12-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_pessoa_pf_pj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='pf',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='pj',
            name='pessoa_ptr',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='PF',
        ),
        migrations.DeleteModel(
            name='PJ',
        ),
    ]
