# Generated by Django 2.2.19 on 2021-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200614_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Rascunho'), ('p', 'Publicado'), ('w', 'Retirado')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
