# Generated by Django 2.2.24 on 2021-07-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210613_0238'),
        ('core', '0008_auto_20210613_0128'),
    ]

    operations = [
    ]
