# Generated by Django 2.2.24 on 2021-08-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20210719_0909'),
        ('core', '0009_merge_20210718_1308'),
    ]

    operations = [
    ]
