# Generated by Django 4.1.3 on 2022-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('description', models.CharField(max_length=300, verbose_name='descrição')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='data de vencimento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor')),
                ('paid', models.BooleanField(default=False, verbose_name='pago?')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('expense.financial',),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('expense.financial',),
        ),
    ]
